[project]
org-name= "wso2"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "utils"
    path = "/home/chamodi/software/utils.jar"
    groupId = "wso2"
    modules = ["utils"]

    [[platform.libraries]]
    artifactId = "abc"
    path = "/home/chamodi/software/mysql-connector-java-5.1.46.jar"
    groupId = "abc"
    modules = ["utils", "issuer", "chat", "doctor", "patient"]